"""
ui_collector_bridge.py — UICollector <-> RecordingSession 桥接层
=================================================================
职责:
  1. 管理 UICollector 实例的生命周期
  2. 接收 RecordingSession 的 mss 截图帧（numpy array），复用截图
  3. 接收 EventListener 的鼠标点击事件，触发控件采集
  4. 输出统一到 inputs/ui_controls/ 目录
  5. 每次点击遍历全部可见控件，输出 YOLO 格式数据集到 dataset/
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import numpy as np
    from .ui_collector import WindowInfo


class UICollectorBridge:
    """UICollector 桥接层，与 RecordingSession 协同工作"""

    def __init__(self, win: WindowInfo, output_dir: Path):
        from .ui_collector import UICollector

        self.win = win
        self.output_dir = output_dir / "inputs" / "ui_controls"
        self.output_dir.mkdir(parents=True, exist_ok=True)

        self.collector = UICollector(
            win=win,
            output_dir=str(self.output_dir),
        )

        # 加载历史数据（如果存在）
        loaded = self.collector.get_storage().load()
        if loaded:
            print(f"  [UICollect] \u5df2\u52a0\u8f7d\u5386\u53f2\u6570\u636e: {self.collector.get_count()} \u4e2a\u63a7\u4ef6")

        self._capture_count = 0
        self._skip_count = 0
        self._traverse_count = 0
        self._bounds_refresh_interval = 5
        self._start_time = time.monotonic()

        # ── YOLO 数据集输出 ──
        self._current_seq = 0
        self._dataset_dir = output_dir / "dataset"
        self._dataset_img_dir = self._dataset_dir / "images"
        self._dataset_lbl_dir = self._dataset_dir / "labels"
        self._dataset_img_dir.mkdir(parents=True, exist_ok=True)
        self._dataset_lbl_dir.mkdir(parents=True, exist_ok=True)
        self._class_names: list[str] = []
        self._load_existing_yaml()

    # ── YOLO data.yaml 管理 ──────────────────────────────────

    def _load_existing_yaml(self) -> None:
        """续录时加载已有类别列表"""
        yaml_path = self._dataset_dir / "data.yaml"
        if yaml_path.exists():
            try:
                import yaml
                with open(yaml_path, encoding="utf-8") as f:
                    data = yaml.safe_load(f)
                self._class_names = data.get("names", [])
                print(f"  [YOLO] \u5df2\u52a0\u8f7d\u73b0\u6709\u6570\u636e\u96c6: {len(self._class_names)} \u4e2a\u7c7b\u522b")
            except Exception:
                self._class_names = []

    def _save_yaml(self) -> None:
        """保存 data.yaml"""
        yaml_path = self._dataset_dir / "data.yaml"
        try:
            with open(yaml_path, "w", encoding="utf-8") as f:
                f.write(f"# Auto-generated by syll-recorder\n")
                f.write(f"nc: {len(self._class_names)}\n")
                f.write("names:\n")
                for name in self._class_names:
                    safe = name.replace('"', "'")
                    f.write(f'  - "{safe}"\n')
        except Exception:
            pass

    # ── 截图复用 ──────────────────────────────────────────────

    def on_screenshot(self, np_array: np.ndarray, seq: int = 0) -> None:
        """接收 RecordingSession 的截图帧 + 序号

        将 numpy 数组转为 PIL.Image 并设置到 collector.screenshot，
        这样 capture_full() 就不用重新截图了。

        Args:
            np_array: BGR 格式的 numpy 数组 (H, W, 3)
            seq: 截图序号（对应 screenshots/{seq:04d}.jpg）
        """
        from PIL import Image
        import numpy as np

        # BGR \u2192 RGB
        rgb = np_array[:, :, ::-1].copy()
        self.collector.screenshot = Image.fromarray(rgb)
        self._current_seq = seq

    # ── 鼠标点击 ──────────────────────────────────────────────

    def on_mouse_click(self, x: int, y: int) -> None:
        """鼠标左键释放回调 \u2014 遍历全部可见控件 + 输出 YOLO 标注

        Args:
            x, y: \u5c4f\u5e55\u5750\u6807
        """
        win = self.win

        # \u68c0\u67e5\u70b9\u51fb\u662f\u5426\u5728\u76ee\u6807\u7a97\u53e3\u5185
        if (x < win.win_left or x > win.win_left + win.win_width or
                y < win.win_top or y > win.win_top + win.win_height):
            return

        self._capture_count += 1
        count = self._capture_count

        try:
            # \u8fb9\u754c\u5237\u65b0\u51b7\u5374
            if count % self._bounds_refresh_interval == 1:
                if hasattr(self.collector.adapter, 'refresh_bounds_silent'):
                    self.collector.adapter.refresh_bounds_silent(win)

            # \u904d\u5386\u5168\u90e8\u53ef\u89c1\u63a7\u4ef6\uff08IsOffscreen \u5df2\u8fc7\u6ee4\u4e0d\u53ef\u89c1\u63a7\u4ef6\uff09
            candidates = self.collector.adapter.collect_all_elements(win)

            # \u5199 YOLO \u6807\u6ce8\uff08\u5728 capture_full \u4e4b\u524d\uff0c\u4fdd\u8bc1 screenshot \u4e3a\u5168\u5c4f\u622a\u56fe\uff09
            self._write_yolo_labels(candidates)

            # \u539f\u6709\uff1a\u8c03\u7528 capture_full \u7ef4\u6301 session.json \u66f4\u65b0
            screenshot, _, new_count = self.collector.capture_full(
                mouse_x=x, mouse_y=y, save_screenshot=False
            )

            total = self.collector.get_count()

            if new_count > 0:
                self._traverse_count += 1
                print(f"  [UICollect] #{count:03d} \U0001f5b1({x},{y}) "
                      f"\u2705 +{new_count} \u65b0\u63a7\u4ef6 (\u5171 {total} \u4e2a)")
            else:
                if len(candidates) == 0:
                    self._skip_count += 1
                else:
                    self._traverse_count += 1
                    print(f"  [UICollect] #{count:03d} \U0001f5b1({x},{y}) "
                          f"\u23ed\ufe0f \u65e0\u65b0\u63a7\u4ef6 (\u5171 {total} \u4e2a)")

        except Exception as e:
            import traceback
            traceback.print_exc()
            print(f"  [UICollect] \u274c \u91c7\u96c6\u5f02\u5e38 #{count}: {e}")

    # ── YOLO 标注输出 ─────────────────────────────────────────

    def _write_yolo_labels(self, candidates: list) -> None:
        """将候选控件写为 YOLO 格式标注文件"""
        if self.collector.screenshot is None or self._current_seq == 0:
            return
        if not candidates:
            return

        img_w, img_h = self.collector.screenshot.size
        win = self.win

        lines = []
        for elem in candidates:
            name = elem.name
            if not name:
                continue
            if name not in self._class_names:
                self._class_names.append(name)
            cls_id = self._class_names.index(name)

            # \u7a97\u53e3\u76f8\u5bf9\u5750\u6807 \u2192 \u5c4f\u5e55\u7edd\u5bf9\u5750\u6807 \u2192 \u5f52\u4e00\u5316
            xc = (elem.bbox_left + elem.bbox_right) / 2 + win.win_left
            yc = (elem.bbox_top + elem.bbox_bottom) / 2 + win.win_top
            w = elem.bbox_right - elem.bbox_left
            h = elem.bbox_bottom - elem.bbox_top

            lines.append(
                f"{cls_id} {xc/img_w:.6f} {yc/img_h:.6f} {w/img_w:.6f} {h/img_h:.6f}"
            )

        if lines:
            # Release 截图标注
            label_path = self._dataset_lbl_dir / f"{self._current_seq:04d}.txt"
            with open(label_path, "w", encoding="utf-8") as f:
                f.write("\n".join(lines) + "\n")
            # Press 截图标注（同一轮点击，控件位置相同）
            press_seq = self._current_seq - 1
            if press_seq > 0:
                press_path = self._dataset_lbl_dir / f"{press_seq:04d}.txt"
                with open(press_path, "w", encoding="utf-8") as f:
                    f.write("\n".join(lines) + "\n")
            self._save_yaml()

    # ── \u751f\u547d\u5468\u671f \u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014

    def stop(self) -> dict:
        """\u505c\u6b62\u91c7\u96c6\uff0c\u4fdd\u5b58\u6570\u636e\uff0c\u590d\u5236\u622a\u56fe\u5230 dataset/images/"""
        # \u4fdd\u5b58 session.json\uff08\u539f\u6709\uff09
        self.collector.get_storage().save()

        # \u4fdd\u5b58 data.yaml
        self._save_yaml()

        # \u590d\u5236 Release \u622a\u56fe\u5230 dataset/images/
        inputs_screenshots = self.output_dir.parent / "screenshots"
        if inputs_screenshots.exists():
            import shutil
            copied = 0
            for lbl_path in self._dataset_lbl_dir.glob("*.txt"):
                stem = lbl_path.stem
                for ext in [".jpg", ".jpeg", ".png"]:
                    src = inputs_screenshots / f"{stem}{ext}"
                    if src.exists():
                        dst = self._dataset_img_dir / f"{stem}{ext}"
                        shutil.copy2(src, dst)
                        copied += 1
                        break
            if copied > 0:
                print(f"  [YOLO] \u5df2\u590d\u5236 {copied} \u5f20\u622a\u56fe\u5230 dataset/images/")

        # \u539f\u6709\u7edf\u8ba1
        total = self.collector.get_count()
        captures = len(self.collector.get_storage().captures)
        elapsed = time.monotonic() - self._start_time
        print(f"  [UICollect] \u91c7\u96c6\u505c\u6b62: {captures} \u6b21\u91c7\u96c6, "
              f"{total} \u4e2a\u63a7\u4ef6, \u8df3\u8fc7 {self._skip_count} \u6b21, "
              f"\u8017\u65f6 {elapsed:.1f}s")

        # YOLO \u6570\u636e\u96c6\u7edf\u8ba1
        lbl_count = len(list(self._dataset_lbl_dir.glob("*.txt")))
        img_count = len(list(self._dataset_img_dir.glob("*.*")))
        print(f"  [YOLO] \u6570\u636e\u96c6: {img_count} \u5f20\u56fe, {lbl_count} \u4e2a\u6807\u6ce8, "
              f"{len(self._class_names)} \u4e2a\u7c7b\u522b")

        return {
            "total_controls": total,
            "captures": captures,
            "skipped": self._skip_count,
            "traversed": self._traverse_count,
            "elapsed_s": round(elapsed, 1),
            "yolo_images": img_count,
            "yolo_labels": lbl_count,
            "yolo_classes": len(self._class_names),
        }
